import "./globals.css";
import { AuthProvider } from "@/public/AuthContext";

export const metadata = {
  title: "Virus Scope",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </AuthProvider>
  );
}
