import "./globals.css";
import { AuthProvider } from "@/app/AuthContext";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata = {
  title: "Virus Scope",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
